# Numpy Summary

### 참고자료 

- Python 데이터 분석 강의
- Numpy Cheet Sheet
- 최성철 교수님 강의자료

In [ ]:
import numpy as np

data1 = [6,7,5,8,0,1]
data2 = [[1,2,3,4],[5,6,7,8]]

In [3]:
arr1 = np.array(data1)
arr1.shape

arr2 = np.array(data2)
arr2.shape

(2, 4)

In [4]:
np.zeros((3,6))
np.zeros([3,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(np.sqrt(arr))
print(np.log10(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[      -inf 0.         0.30103    0.47712125 0.60205999 0.69897
 0.77815125 0.84509804 0.90308999 0.95424251]


C:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log10
  


In [61]:
# 데이터 타입 체크 및 변경
arr = np.array([1,2,3,4,5],dtype=np.int64)
arr = arr.astype(np.float64)
arr.dtype

dtype('float64')

In [59]:
# 원소별 연산

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

print(arr1*2)
print(arr1**0.5)
print(1/arr1)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [70]:
# 원소 추출 및 변경

arr = np.arange(10)
print(arr[5])
print(arr[5:8])
arr[5:8]= 12
print(arr)

5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [88]:
# Boolean Index 
names = np.array(["criss","ken","junha","hayoung","suna","jinhyoung"])
data = np.random.randn(6,3)
print(names == "criss")
print(data[names=="criss"])

[ True False False False False False]
[[ 0.5897861  -0.68564942 -0.54906718]]


In [78]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

print(arr2d[2,:]) # 3행
print(arr2d[1:3,:]) # 2~3행
print(arr2d[:,3]) # 4열

# 4행 3열 값 변경
arr2d[3,2] = 13
print(arr2d)

# 3행 2,3열 값 변경
arr2d[2,1:3] = 0
print(arr2d)

[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[ 4  8 12 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 13 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9  0  0 12]
 [13 14 13 16]]


In [ ]:
# 난수 생성
x = np.random.randn(8)
y = np.random.randn(8)

In [ ]:
# 성분별 최대값
np.maximum(x,y) 

In [19]:
# 행/열 연산
arr = np.random.rand(5,4)
arr.sum()
arr.mean()
arr.sum(axis=0) # 행방향 합
arr.sum(axis=1) # 열방향 합



array([1.20033296, 2.15229085, 2.8289407 , 0.69521974, 2.95042411])

In [16]:
# 조건부 합
arr > 0

(arr>0).sum()

20

In [50]:
# 정렬
arr = np.random.randn(8)
print(arr)
print(np.sort(arr))

# 내림차순 정렬
print(np.sort(arr)[::-1])

[ 0.01308689  0.99978079  0.96885249 -0.69992385 -1.17116998 -0.06045624
  0.06375012  0.06861638]
[-1.17116998 -0.69992385 -0.06045624  0.01308689  0.06375012  0.06861638
  0.96885249  0.99978079]
[ 0.99978079  0.96885249  0.06861638  0.06375012  0.01308689 -0.06045624
 -0.69992385 -1.17116998]


In [51]:
# 정렬
arr = np.random.randn(3,3)
print(np.sort(arr,axis=0)) # 행 정렬
print(np.sort(arr,axis=1)) # 열 정렬

[[-0.76535956 -0.96558965 -0.47831786]
 [ 0.17843261  0.80197315 -0.03054377]
 [ 0.35225766  1.48197051  0.20300216]]
[[-0.96558965 -0.47831786  0.35225766]
 [ 0.17843261  0.20300216  0.80197315]
 [-0.76535956 -0.03054377  1.48197051]]


In [63]:
# 상위 5%의 값

large_arr = np.random.randn(30)
np.sort(large_arr)[::-1][int(0.05*len(large_arr))]

1.5830308158226412

In [91]:
ints = np.array([3,3,3,2,2,1,1,4,4])
print(np.unique(names))
print(np.unique(ints))

['criss' 'hayoung' 'jinhyoung' 'junha' 'ken' 'suna']
[1 2 3 4]
